FROM ek-gpu-base AS ek-base

ARG PROXY
ARG PY_VERSION=3.12

ENV HTTP_PROXY=${PROXY}
ENV HTTPS_PROXY=${PROXY}
ENV http_proxy=${PROXY}
ENV https_proxy=${PROXY}
ENV no_proxy="localhost,127.0.0.1,::1,mirrors.tuna.tsinghua.edu.cn"
ENV NO_PROXY="localhost,127.0.0.1,::1,mirrors.tuna.tsinghua.edu.cn"

ENV UV_CACHE_DIR="/opt/uv-cache"
ENV UV_HOME="/opt/uv-python"
ENV UV_PYTHON="python${PY_VERSION}"

ENV PATH="${UV_HOME}/bin:${PATH}"

ENV UV_INSTALL_DIR="${UV_HOME}/bin"

WORKDIR /ek

####################### Expert Kit Build ####################### 
## Build dependencies
RUN cargo new --lib ek-base && \
    cargo new --lib ek-benchmark && \
    cargo new --lib ek-computation && \
    cargo new --lib ek-db && \
    cargo new --lib ek-cli && \
    cargo new --lib ek-ggml && \
    cargo new --lib ek-integration/expertkit-transport-rs
## Create dummy folders and dependent files
RUN mkdir -p ek-computation/benches && \
    cd ek-computation/benches && echo "fn main() {}" > main.rs
## Copy dependencies
COPY ek-base/Cargo.toml ./ek-base/
COPY ek-benchmark/Cargo.toml ./ek-benchmark/
COPY ek-computation/Cargo.toml ./ek-computation/
COPY ek-cli/Cargo.toml ./ek-cli/
COPY ek-db/Cargo.toml ./ek-db/
COPY ek-ggml/Cargo.toml ./ek-ggml/
COPY ek-integration/expertkit-transport-rs/Cargo.toml ./ek-integration/expertkit-transport-rs
COPY Cargo.toml ./Cargo.lock ./
RUN cargo build --release --lib && \
cargo clean # this cleans up caches but keeps internet downloads

COPY ek-integration/expertkit-transport-rs ./ek-integration/expertkit-transport-rs
RUN touch ./ek-integration/expertkit-transport-rs/src/lib.rs && \
cargo build --release && \
cargo clean # this cleans up caches but keeps internet downloads
####################### Expert Kit Build ####################### 

## Download uv & python essentials
RUN apt-get update && \
apt-get install -y \ 
"pip" 

## UV settings and set up global python version
RUN mkdir -p ${UV_CACHE_DIR} && mkdir -p ${UV_HOME} && \
curl -LsSf https://astral.sh/uv/install.sh | sh && \
uv python install ${PY_VERSION}

####################### Expert Kit (Attn) ####################### 
COPY uv.lock ./uv.lock
COPY pyproject.toml ./pyproject.toml
COPY ek-integration/expertkit_torch ./ek-integration/expertkit_torch
COPY ek-integration/expertkit_vllm ./ek-integration/expertkit_vllm
####################### Expert Kit (Attn) ####################### 

RUN chmod -R 777 /ek ${CARGO_HOME} ${UV_CACHE_DIR} ${UV_HOME} /etc/expert-kit /tmp/expert-kit/cache # makes sure each user has read/write/execute permission
RUN git config --system --add safe.directory '*'  # allows git to operate on root-owned directories

# Unset proxy
ENV HTTP_PROXY=""
ENV HTTPS_PROXY=""
ENV http_proxy=""
ENV https_proxy=""

EXPOSE 22 

CMD [ "/usr/local/bin/entrypoint" ]
