FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04 AS sys-base

####################### Variables ####################### 
# Dockerfile args (alive in docker image build)
ARG BUILD_PROXY
ARG DEPLOY_PROXY
ARG TORCH_VERSION=2.7.0
ARG TORCH_CUDA_ARCH=cu126
ARG LIBTORCH_URL="https://download.pytorch.org/libtorch/${TORCH_CUDA_ARCH}/libtorch-cxx11-abi-shared-with-deps-${TORCH_VERSION}%2B${TORCH_CUDA_ARCH}.zip"
ARG TMP_LIBTORCH_ZIP="/tmp/libtorch.zip"

# Enviromental vars (alive in docker container)
ENV HTTP_PROXY=${BUILD_PROXY}
ENV HTTPS_PROXY=${BUILD_PROXY}
ENV http_proxy=${BUILD_PROXY}
ENV https_proxy=${BUILD_PROXY}
ENV no_proxy="localhost,127.0.0.1,::1,mirrors.tuna.tsinghua.edu.cn"
ENV NO_PROXY="localhost,127.0.0.1,::1,mirrors.tuna.tsinghua.edu.cn"

ENV LIBTORCH_BASE_DIR=/opt/torch
ENV LIBTORCH=${LIBTORCH_BASE_DIR}/libtorch
ENV LD_LIBRARY_PATH="${LIBTORCH}/lib:${LD_LIBRARY_PATH}"

# Rust Related
ENV CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=1"
# Set up the cargo mirror
ENV RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
ENV RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
####################### Variables ####################### 

####################### System Settings ####################### 
## Replace apt offical sources with mirrors
RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list && \
    sed -i 's@//security.ubuntu.com@//mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list

## Essential packages (heavy)
RUN apt-get update && \
apt-get install -y \
"openssh-server" "openssh-client" "sudo" "build-essential" "iputils-ping" "net-tools" \
"htop" "nvtop" "tree" "tmux" "netcat-openbsd" "entr" "xsel" \
"wget" "curl" "aria2" "lshw" "kmod" "pkg-config" "unzip" "git-lfs" \
"cmake" "rdma-core" "clang" "protobuf-compiler" "vim" \
"python3" "python3-pip" "python3-venv" && \
rm -rf /var/lib/apt/lists/*  # clean up apt cache
####################### System Settings ####################### 

####################### Expert Kit Prerequisites ####################### 
## Prerequisites for expert-kit (light and subject to change)
RUN apt-get update && \
apt-get install -y \ 
"infiniband-diags" "perftest" "ibverbs-providers" "libibumad3" "libibverbs1" "libnl-3-200" "libnl-route-3-200" "librdmacm1" \ 
"libibverbs-dev" "libclang-dev" "libpq-dev" && \
rm -rf /var/lib/apt/lists/*  # clean up apt cache

WORKDIR /

## Libtorch dependency
RUN mkdir -p ${LIBTORCH_BASE_DIR} && \
aria2c --all-proxy="${BUILD_PROXY}" -x 16 -s 16 -k 1M ${LIBTORCH_URL} -o ${TMP_LIBTORCH_ZIP} && \
unzip ${TMP_LIBTORCH_ZIP} -d ${LIBTORCH_BASE_DIR} && \
rm ${TMP_LIBTORCH_ZIP} 

####################### Expert Kit Prerequisites ####################### 

####################### SSHD Settings ####################### 
RUN mkdir -p /var/run/sshd /root/.ssh && \
sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config && \
sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/sshd_config

# Add teammate script to /usr/local/bin
COPY ./scripts/add_teammate.sh /usr/local/bin/add_teammate
RUN chmod +x /usr/local/bin/add_teammate

# ek-env.sh will be automatically sourced if moved to /etc/profile.d
COPY ./scripts/ek-env.sh /etc/profile.d/ek-env.sh

# Add pub key to root for login
COPY ./.secrets/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
####################### SSHD Settings ####################### 

EXPOSE 22

ENV HTTP_PROXY=${DEPLOY_PROXY}
ENV HTTPS_PROXY=${DEPLOY_PROXY}
ENV http_proxy=${DEPLOY_PROXY}
ENV https_proxy=${DEPLOY_PROXY}
ENV no_proxy="localhost,127.0.0.1,::1,10.0.0.0/8,192.168.0.0/16,mirrors.tuna.tsinghua.edu.cn"
ENV NO_PROXY=${no_proxy}

CMD [ "/usr/sbin/sshd", "-De" ]
